/* eslint-disable no-magic-numbers */
module.exports = {
  rules: {
    'line-comment-position': 'error',
    'lines-between-class-members': 'error',
    'max-statements-per-line': ['error', { max: 2 }],
    /*
     * // Useless
     * 'comma-dangle': 'off',
     * 'no-extra-parens': 'off',
     * 'no-tabs': 'off',
     * 'padding-line-between-statements': 'off',
     * 'unicode-bom': 'off',
     * // Overrided by prettier
     * 'array-bracket-newline': [
     *   'error',
     *   {
     *     multiline: true,
     *     minItems: 5,
     *   },
     * ],
     * 'array-bracket-spacing': 'error',
     * 'array-element-newline': ['error', 'never', { multiline: true }],
     * 'arrow-parens': ['error', 'as-needed'],
     * 'arrow-spacing': 'error',
     * 'block-spacing': 'error',
     * 'brace-style': 'error',
     * 'comma-spacing': 'error',
     * 'comma-style': 'error',
     * 'computed-property-spacing': 'error',
     * 'dot-location': ['error', 'property'],
     * 'eol-last': 'error',
     * 'func-call-spacing': 'error',
     * 'function-call-argument-newline': ['error', 'never'],
     * 'function-paren-newline': 'error',
     * 'generator-star-spacing': ['error', 'after'],
     * 'implicit-arrow-linebreak': 'error',
     * indent: ['error', 2],
     * 'jsx-quotes': 'error',
     * 'key-spacing': ['error', { mode: 'strict' }],
     * 'keyword-spacing': 'error',
     * 'linebreak-style': 'error',
     * 'lines-around-comment': 'off',
     * 'max-len': 'error',
     * 'multiline-ternary': ['error', 'never'],
     * 'new-parens': 'error',
     * 'newline-per-chained-call': ['error', { ignoreChainWithDepth: 3 }],
     * 'no-multi-spaces': 'error',
     * 'no-multiple-empty-lines': [
     *   'error',
     *   {
     *     max: 1,
     *     maxEOF: 1,
     *   },
     * ],
     * 'no-trailing-spaces': 'error',
     * 'no-whitespace-before-property': 'error',
     * 'nonblock-statement-body-position': 'error',
     * 'object-curly-newline': [
     *   'error',
     *   {
     *     multiline: true,
     *     minProperties: 5,
     *   },
     * ],
     * 'object-curly-spacing': 'error',
     * 'object-property-newline': 'error',
     * 'operator-linebreak': ['error', 'after'],
     * 'padded-blocks': ['error', 'never'],
     * quotes: ['error', 'single'],
     * 'rest-spread-spacing': ['error', 'never'],
     * semi: 'error',
     * 'semi-spacing': 'error',
     * 'semi-style': 'error',
     * 'space-before-blocks': 'error',
     * 'space-before-function-paren': ['error', 'never'],
     * 'space-in-parens': 'error',
     * 'space-infix-ops': 'error',
     * 'space-unary-ops': 'error',
     * 'switch-colon-spacing': 'error',
     * 'template-curly-spacing': 'error',
     * 'template-tag-spacing': 'error',
     * 'wrap-iife': ['error', 'inside'],
     * 'wrap-regex': 'error',
     * 'yield-star-spacing': ['error', 'after'],
     */
  },
};
