/* eslint-disable no-magic-numbers */
/* eslint-disable no-warning-comments */
/* eslint-disable line-comment-position */
/* eslint-disable no-inline-comments */
module.exports = {
  rules: {
    'accessor-pairs': 'error',
    'arrow-body-style': ['error', 'as-needed'],
    'block-scoped-var': 'error',
    camelcase: 'error',
    'capitalized-comments': ['warn', 'always'],
    'class-methods-use-this': 'error',
    complexity: ['warn', 5], // Lower is better but harder for large projects
    'consistent-this': ['error', 'that'],
    'default-case': 'error',
    'default-case-last': 'error',
    'default-param-last': 'error',
    'dot-notation': 'error',
    eqeqeq: 'error',
    'func-name-matching': 'error',
    'func-names': ['error', 'as-needed'],
    'grouped-accessor-pairs': 'error',
    'id-length': ['error', { exceptions: ['_'] }], // Default 2 min
    'max-classes-per-file': 'error',
    'max-depth': 'warn',
    'max-lines': 'warn',
    'max-lines-per-function': 'warn',
    'max-nested-callbacks': 'warn',
    'max-params': ['warn', 5],
    'max-statements': 'warn',
    'multiline-comment-style': 'warn',
    'new-cap': 'error',
    'no-alert': 'error',
    'no-array-constructor': 'error',
    'no-bitwise': 'error',
    'no-caller': 'error',
    'no-console': 'error',
    'no-continue': 'error',
    'no-div-regex': 'error',
    'no-empty-function': 'error',
    'no-empty-static-block': 'error',
    'no-eval': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-extra-label': 'error',
    'no-implicit-coercion': ['error', { allow: ['!!'] }],
    'no-implied-eval': 'error',
    'no-inline-comments': 'warn',
    'no-invalid-this': 'error',
    'no-iterator': 'error',
    'no-label-var': 'error',
    'no-lone-blocks': 'error',
    'no-lonely-if': 'error',
    'no-loop-func': 'error',
    'no-magic-numbers': 'warn',
    'no-multi-assign': 'warn',
    'no-multi-str': 'error',
    'no-negated-condition': 'error',
    'no-nested-ternary': 'warn',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-object': 'error',
    'no-new-wrappers': 'error',
    'no-octal-escape': 'warn',
    'no-param-reassign': 'error',
    'no-proto': 'error',
    'no-return-assign': 'warn',
    'no-return-await': 'warn',
    'no-script-url': 'error',
    'no-sequences': 'error',
    'no-shadow': 'warn',
    'no-throw-literal': 'error',
    'no-undef-init': 'error',
    'no-undefined': 'error',
    'no-underscore-dangle': 'error',
    'no-unneeded-ternary': 'error',
    'no-unused-expressions': 'error',
    'no-useless-call': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-concat': 'error',
    'no-useless-constructor': 'error',
    'no-useless-rename': 'error',
    'no-useless-return': 'error',
    'no-var': 'error',
    'no-void': 'error',
    'no-warning-comments': 'warn',
    'object-shorthand': 'error',
    'prefer-promise-reject-errors': 'error',
    'prefer-rest-params': 'warn',
    'prefer-template': 'warn',
    radix: 'error',
    'require-await': 'error',
    'require-unicode-regexp': 'error',
    'sort-imports': 'error',
    'spaced-comment': 'error',
    'vars-on-top': 'error',
    /*
     * // Useless
     * 'consistent-return': 'off',
     * 'func-style': 'off',
     * 'guard-for-in': 'off',
     * 'id-denylist': 'off',
     * 'id-match': 'off',
     * 'init-declarations': 'off',
     * 'logical-assignment-operators': 'off',
     * 'no-else-return': 'off',
     * 'no-implicit-globals': 'off',
     * 'no-labels': 'off',
     * 'no-plusplus': 'off',
     * 'no-restricted-exports': 'off',
     * 'no-restricted-globals': 'off',
     * 'no-restricted-imports': 'off',
     * 'no-restricted-properties': 'off',
     * 'no-restricted-syntax': 'off',
     * 'no-ternary': 'off',
     * 'one-var': 'off',
     * 'one-var-declaration-per-line': 'off',
     * 'operator-assignment': 'off',
     * 'prefer-arrow-callback': 'off',
     * 'prefer-const': 'off',
     * 'prefer-destructuring': 'off',
     * 'prefer-exponentiation-operator': 'off',
     * 'prefer-named-capture-group': 'off',
     * 'prefer-numeric-literals': 'off',
     * 'prefer-object-has-own': 'off',
     * 'prefer-object-spread': 'off',
     * 'prefer-regex-literals': 'off',
     * 'prefer-spread': 'off',
     * 'sort-keys': 'off',
     * 'sort-vars': 'off',
     * strict: 'off',
     * 'symbol-description': 'off',
     * yoda: 'off',
     * // Overrided by eqeqeq rule
     * 'no-eq-null': 'error',
     * // Overrided by prettier
     * curly: ['error', 'multi-or-nest'],
     * 'no-confusing-arrow': 'error',
     * 'no-floating-decimal': 'error',
     * 'no-mixed-operators': 'error',
     * 'quote-props': ['error', 'as-needed'],
     */
  },
};
